-- Generated by concatenating 00-*.sql .. 03-*.sql in order. Re-run scripts/build-schema.js after editing table-definitions.
\i 00-enums-schema.sql
\i 01-iam-schema.sql
\i 02-operation-schema.sql
\i 03-marketplace-schema.sql
